services:
  mysql:
    image: mysql:8.0.37
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: libreria
    ports:
      - "3306:3306"
    volumes:
      - ./libreria.sql:/docker-entrypoint-initdb.d/libreria.sql
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -e 'SELECT 1'"]
      interval: 5s
      timeout: 10s
      retries: 15

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/libreria?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true&connectTimeout=30000
      SPRING_DATASOURCE_USERNAME: root
    depends_on:
      mysql:
        condition: service_healthy